spring:
  application:
    name: coupon-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupons}
    username: ${DB_USERNAME:coupons}
    password: ${DB_PASSWORD:coupons}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.coupons: INFO
