--liquibase formatted sql

--changeset coupon-service:20260831-1430-create-coupon
--comment: Coupon aggregate storage. Code is stored normalized (lower-case) with a plain UNIQUE index, giving case-insensitive uniqueness. Every coupon is country-restricted, so country is required.
CREATE TABLE coupon (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_coupon PRIMARY KEY,
    code         VARCHAR(64)              NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    max_uses     INT                      NOT NULL,
    current_uses INT                      NOT NULL DEFAULT 0,
    country      CHAR(2)                  NOT NULL
);
ALTER TABLE coupon ADD CONSTRAINT uq_coupon_code UNIQUE (code);
-- Defense-in-depth guards on the usage counter.
ALTER TABLE coupon
    ADD CONSTRAINT ck_coupon_max_uses_positive        CHECK (max_uses > 0),
    ADD CONSTRAINT ck_coupon_current_uses_non_negative CHECK (current_uses >= 0),
    ADD CONSTRAINT ck_coupon_current_within_max        CHECK (current_uses <= max_uses);
--rollback DROP TABLE coupon;
