--liquibase formatted sql

--changeset coupon-service:20260831-1435-create-coupon-redemption
--comment: One row per registered redemption. UNIQUE(coupon_id, user_id) makes "one redemption per user" a database invariant.
CREATE TABLE coupon_redemption (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_coupon_redemption PRIMARY KEY,
    coupon_id        BIGINT                   NOT NULL CONSTRAINT fk_redemption_coupon REFERENCES coupon (id),
    user_id          VARCHAR(200)             NOT NULL,
    redeemed_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    resolved_country CHAR(2)                  NOT NULL
);
ALTER TABLE coupon_redemption ADD CONSTRAINT uq_redemption_coupon_user UNIQUE (coupon_id, user_id);
CREATE INDEX ix_redemption_coupon ON coupon_redemption (coupon_id);
--rollback DROP TABLE coupon_redemption;
